alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: www.salcommercialflooring.com
  type: PRIMARY
  zone: salcommercialflooring.com
name: salcomercialflooring
region: tor
static_sites:
- environment_slug: html
  github:
    branch: master
    repo: estebanmendez97/Salcomercialflooring
  name: salcomercialflooring
  routes:
  - path: /
  source_dir: /